### PR TITLE
Milestone 1: Implement Our Enumerable

### PR DESCRIPTION
**Pull request by binyamolango**
# Hi Reviewer 👋

> Me @binyamolango and my partner @ishimwepati Implemented the following changes to the project.

1. Made sure that we understand what the #any?, #all?, and filter methods are doing by Checking the official documentation of Enumerable.

2. Created a class MyList that has an instance variable @list.
3. Implemented a method #each in the MyList class that yields successive members of @list and uses the MyEnumerable module.
4. Created a module MyEnumerable that implements the #any?, #all?, and filter methods.

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has incorrect gitflow/ GitHub flow. Kindly note that the Pull Request for this activity should flow **from feature into development**. Kindly use the correct gitflow and request another code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by binyamolango** [comment]
Hi @rloterh, we are very much grateful for taking the time to review our project. We have submitted our project previously by creating our pull request from the featured branch to the main branch, but the last reviewer made our pull request invalid and told us to use the correct gitflow by following this [guideline](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) (I guess gitflow is different for different modules). I closed that pull request and created this new one by following the suggested gitflow. I attached a screenshot of it. We are getting confused here. We would appreciate hearing your feedback. Thank you.
Screenshot 2023-10-14 231904

**Review by DammyShittu — APPROVED** [review]
Hi @binyamolango and @ishimwepati,

## APPROVED 🟢

## Highlights
✔️ Custom enumerables

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by binyamolango** [comment]
Hi @DammyShittu, Thank you for reviewing and approving our project.

**Pull request merged**
